inst_list = {
    "BTC-USD": "Bitcoin USD",
    "ETH-USD": "Ethereum USD",
    "USDT-USD": "Tether USD",
    "BNB-USD": "BNB USD",
    "USDC-USD": "USD Coin USD",
    "XRP-USD": "XRP USD",
    "ADA-USD": "Cardano USD",
    "STETH-USD": "Lido Staked ETH USD",
    "DOGE-USD": "Dogecoin USD",
    "MATIC-USD": "Polygon USD",
    "SOL-USD": "Solana USD",
    "WTRX-USD": "Wrapped TRON USD",
    "LTC-USD": "Litecoin USD",
    "TRX-USD": "TRON USD",
    "DOT-USD": "Polkadot USD",
    "HEX-USD": "HEX USD",
    "BUSD-USD": "Binance USD USD",
    "SHIB-USD": "Shiba Inu USD",
    "DAI-USD": "Dai USD",
    "AVAX-USD": "Avalanche USD",
    "WBTC-USD": "Wrapped Bitcoin USD",
    "LEO-USD": "UNUS SED LEO USD",
    "LINK-USD": "Chainlink USD",
    "ATOM-USD": "Cosmos USD",
    "UNI7083-USD": "Uniswap USD",
    "XMR-USD": "Monero USD",
    "OKB-USD": "OKB USD",
    "ETC-USD": "Ethereum Classic USD",
    "XLM-USD": "Stellar USD",
    "TON11419-USD": "Toncoin USD",
    "ICP-USD": "Internet Computer USD",
    "BCH-USD": "Bitcoin Cash USD",
    "CNX-USD": "Cryptonex USD",
    "TUSD-USD": "TrueUSD USD",
    "FIL-USD": "Filecoin USD",
    "LDO-USD": "Lido DAO USD",
    "WHBAR-USD": "Wrapped HBAR USD",
    "HBAR-USD": "Hedera USD",
    "APT21794-USD": "Aptos USD",
    "CRO-USD": "Cronos USD",
    "NEAR-USD": "NEAR Protocol USD",
    "ARB11841-USD": "Arbitrum USD",
    "BTCB-USD": "Bitcoin BEP2 USD",
    "VET-USD": "VeChain USD",
    "APE18876-USD": "ApeCoin USD",
    "QNT-USD": "Quant USD",
    "ALGO-USD": "Algorand USD",
    "GRT6719-USD": "The Graph USD",
    "FTM-USD": "Fantom USD",
    "USDP-USD": "Pax Dollar USD",
    "FRAX-USD": "Frax USD",
    "WBNB-USD": "Wrapped BNB USD",
    "SAND-USD": "The Sandbox USD",
    "RPL-USD": "Rocket Pool USD",
    "EOS-USD": "EOS USD",
    "WEOS-USD": "Wrapped EOS USD",
    "BIT11221-USD": "BitDAO USD",
    "EGLD-USD": "MultiversX USD",
    "AAVE-USD": "Aave USD",
    "STX4847-USD": "Stacks USD",
    "MANA-USD": "Decentraland USD",
    "RNDR-USD": "Render Token USD",
    "THETA-USD": "Theta Network USD",
    "CFX-USD": "Conflux USD",
    "XTZ-USD": "Tezos USD",
    "AXS-USD": "Axie Infinity USD",
    "FLOW-USD": "Flow USD",
    "CHZ-USD": "Chiliz USD",
    "USDD-USD": "USDD USD",
    "XRD-USD": "Radix USD",
    "KCS-USD": "KuCoin Token USD",
    "CRV-USD": "Curve DAO Token USD",
    "BGB-USD": "Bitget Token USD",
    "IMX10603-USD": "Immutable USD",
    "PEPE24478-USD": "Pepe USD",
    "BSV-USD": "Bitcoin SV USD",
    "NEO-USD": "Neo USD",
    "SNX-USD": "Synthetix USD",
    "TNC5524-USD": "TNC Coin USD",
    "MKR-USD": "Maker USD",
    "SUI20947-USD": "Sui USD",
    "BTTOLD-USD": "BitTorrent USD",
    "GUSD-USD": "Gemini Dollar USD",
    "BTT-USD": "BitTorrent(New) USD",
    "INJ-USD": "Injective USD",
    "KAVA-USD": "Kava USD",
    "OP-USD": "Optimism USD",
    "KLAY-USD": "Klaytn USD",
    "CSPR-USD": "Casper USD",
    "GMX11857-USD": "GMX USD",
    "PAXG-USD": "PAX Gold USD",
    "ZEC-USD": "Zcash USD",
    "LUNC-USD": "Terra Classic USD",
    "MINA-USD": "Mina USD",
    "WKAVA-USD": "Wrapped Kava USD",
    "FXS-USD": "Frax Share USD",
    "XEC-USD": "eCash USD",
    "DASH-USD": "Dash USD",
    "MIOTA-USD": "IOTA USD",
    "XAUT-USD": "Tether Gold USD",
    "GT-USD": "GateToken USD",
    "HT-USD": "Huobi Token USD",
    "FLR-USD": "Flare USD",
    "XDC-USD": "XDC Network USD",
    "TWT-USD": "Trust Wallet Token USD",
    "LRC-USD": "Loopring USD",
    "WOO-USD": "WOO Network USD",
    "NEXO-USD": "Nexo USD",
    "ZIL-USD": "Zilliqa USD",
    "RUNE-USD": "THORChain USD",
    "MASK8536-USD": "Mask Network USD",
    "CAKE-USD": "PancakeSwap USD",
    "CVX-USD": "Convex Finance USD",
    "AGIX-USD": "SingularityNET USD",
    "FTT-USD": "FTX Token USD",
    "ENJ-USD": "Enjin Coin USD",
    "DYDX-USD": "dYdX USD",
    "BAT-USD": "Basic Attention Token USD",
    "1INCH-USD": "1inch Network USD",
    "BABYDOGE-USD": "Baby Doge Coin USD",
    "FLOKI-USD": "FLOKI USD",
    "USDJ-USD": "USDJ USD",
    "KAS-USD": "Kaspa USD",
    "ROSE-USD": "Oasis Network USD",
    "OSMO-USD": "Osmosis USD",
    "GNO-USD": "Gnosis USD",
    "XEM-USD": "NEM USD",
    "ENS-USD": "Ethereum Name Service USD",
    "MX-USD": "MX TOKEN USD",
    "HOT2682-USD": "Holo USD",
    "LUSD-USD": "Liquity USD USD",
    "RVN-USD": "Ravencoin USD",
    "QTUM-USD": "Qtum USD",
    "BAL-USD": "Balancer USD",
    "TFUEL-USD": "Theta Fuel USD",
    "CELO-USD": "Celo USD",
    "COMP5692-USD": "Compound USD",
    "XCH-USD": "Chia USD",
    "ANKR-USD": "Ankr USD",
    "AUDIO-USD": "Audius USD",
    "DCR-USD": "Decred USD",
    "DFI-USD": "DeFiChain USD",
    "ORDI-USD": "Ordinals USD",
    "LUNA20314-USD": "Terra USD",
    "HBTC-USD": "Huobi BTC USD",
    "LN-USD": "LINK USD",
    "ICX-USD": "ICON USD",
    "SXP-USD": "Solar USD",
    "SSV-USD": "ssv.network USD",
    "GMT18069-USD": "STEPN USD",
    "T-USD": "Threshold USD",
    "ASTR-USD": "Astar USD",
    "JASMY-USD": "JasmyCoin USD",
    "BDX-USD": "Beldex USD",
    "BTG-USD": "Bitcoin Gold USD",
    "AR-USD": "Arweave USD",
    "ETHW-USD": "EthereumPoW USD",
    "BLUR-USD": "Blur USD",
    "WEMIX-USD": "WEMIX USD",
    "ONE3945-USD": "Harmony USD",
    "YFI-USD": "yearn.finance USD",
    "KSM-USD": "Kusama USD",
    "IOTX-USD": "IoTeX USD",
    "GLM-USD": "Golem USD",
    "RON14101-USD": "Ronin USD",
    "GALA-USD": "Gala USD",
    "EDGT-USD": "Edgecoin USD",
    "JST-USD": "JUST USD",
    "FET-USD": "Fetch.ai USD",
    "HNT-USD": "Helium USD",
    "SUSHI-USD": "SushiSwap USD",
    "OCEAN-USD": "Ocean Protocol USD",
    "DAO-USD": "DAO Maker USD",
    "MAGIC14783-USD": "MAGIC USD",
    "LYXE-USD": "LUKSO USD",
    "ONT-USD": "Ontology USD",
    "ZRX-USD": "0x Protocol USD",
    "WAXP-USD": "WAX USD",
    "BAND-USD": "Band Protocol USD",
    "WAVES-USD": "Waves USD",
    "SC-USD": "Siacoin USD",
    "GLMR-USD": "Moonbeam USD",
    "KDA-USD": "Kadena USD",
    "HIVE-USD": "Hive USD",
    "IOST-USD": "IOST USD",
    "POLY-USD": "POLY Maximus USD",
    "ELF-USD": "aelf USD",
    "BONE11865-USD": "Bone ShibaSwap USD",
    "EDU24613-USD": "Open Campus USD",
    "XYM-USD": "Symbol USD",
    "BICO-USD": "Biconomy USD",
    "ASTRAFER-USD": "Astrafer USD",
    "ACH-USD": "Alchemy Pay USD",
    "CELR-USD": "Celer Network USD",
    "BORA-USD": "BORA USD",
    "GNS-USD": "Gains Network USD",
    "SFP-USD": "SafePal USD",
    "UMA-USD": "UMA USD",
    "RSR-USD": "Reserve Rights USD",
    "USTC-USD": "TerraClassicUSD USD",
    "BNX23635-USD": "BinaryX USD",
    "TRIBE-USD": "Tribe USD",
    "ID21846-USD": "SPACE ID USD",
    "SKL-USD": "SKALE USD",
    "FLUX-USD": "Flux USD",
    "TOMI23246-USD": "tomiNet USD",
    "ANT-USD": "Aragon USD",
    "CHSB-USD": "SwissBorg USD",
    "ABBC-USD": "ABBC Coin USD",
    "MOB-USD": "MobileCoin USD",
    "CKB-USD": "Nervos Network USD",
    "LPT-USD": "Livepeer USD",
    "CTSI-USD": "Cartesi USD",
    "EURS-USD": "STASIS EURO USD",
    "WBETH-USD": "Wrapped Beacon ETH USD",
    "DGB-USD": "DigiByte USD",
    "ILV-USD": "Illuvium USD",
    "RIF-USD": "RSK Infrastructure Framework USD",
    "AXL17799-USD": "Axelar USD",
    "BRISE-USD": "Bitgert USD",
    "RLC-USD": "iExec RLC USD",
    "KEEP-USD": "Keep Network USD",
    "AMP-USD": "Amp USD",
    "STORJ-USD": "Storj USD",
    "Cocos-BCX": "Cocos-BCX USD",
    "JOE-USD": "JOE USD",
    "TEL-USD": "Telcoin USD",
    "STG18934-USD": "Stargate Finance USD",
    "LQTY-USD": "Liquity USD",
    "SURE-USD": "inSure DeFi USD",
    "MULTI17050-USD": "Multichain USD",
    "OMG-USD": "OMEGA FINANCE USD",
    "ZEN-USD": "Horizen USD",
    "BTRST-USD": "Braintrust USD",
    "ELON-USD": "Dogelon Mars USD",
    "VVS-USD": "VVS Finance USD",
    "LSK-USD": "Lisk USD",
    "CNNC-USD": "Cannation USD",
    "TOMO-USD": "TomoChain USD",
    "GAL11877-USD": "Galxe USD",
    "API3-USD": "API3 USD",
    "VUSDC-USD": "Venus USDC USD",
    "KNC-USD": "Kyber Network Crystal v2 USD",
    "TRAC-USD": "OriginTrail USD",
    "PUNDIX-USD": "Pundi X (New) USD",
    "PLA7461-USD": "PlayDapp USD",
    "DEL-USD": "Decimal USD",
    "RAD-USD": "Radicle USD",
    "AVINOC-USD": "AVINOC USD",
    "NFT9816-USD": "APENFT USD",
    "MLK-USD": "MiL.k USD",
    "METIS-USD": "MetisDAO USD",
    "CORE23254-USD": "Core USD",
    "HUM-USD": "Humanscape USD",
    "MED-USD": "MediBloc USD",
    "POLYX-USD": "Polymesh USD",
    "SCRT-USD": "Secret USD",
    "XNO-USD": "Nano USD",
    "PENDLE-USD": "Pendle USD",
    "FLEX-USD": "FLEX USD",
    "RBTC-USD": "Rootstock Smart Bitcoin USD",
    "FGC-USD": "FantasyGold USD",
    "CHR-USD": "Chromia USD",
    "C98-USD": "Coin98 USD",
    "SLP-USD": "Smooth Love Potion USD",
    "DEXE-USD": "DeXe USD",
    "PYR-USD": "Pyroblock USD",
    "SNT-USD": "Status USD",
    "DESO-USD": "Decentralized Social USD",
    "MC-USD": "Merit Circle USD",
    "SYS-USD": "Syscoin USD",
    "ARAW-USD": "ARAW USD",
    "ESCE-USD": "Escroco Emerald USD",
    "USDX6651-USD": "USDX [Kava] USD",
    "PEOPLE-USD": "ConstitutionDAO USD",
    "CVC-USD": "Civic USD",
    "REQ-USD": "Request USD",
    "NMR-USD": "Numeraire USD",
    "GTC10052-USD": "Gitcoin USD",
    "HFT22461-USD": "Hashflow USD",
    "ONG3217-USD": "Ontology Gas USD",
    "STPT-USD": "STP USD",
    "MRS21178-USD": "Metars Genesis USD",
    "WILD-USD": "Wilder World USD",
    "STEEM-USD": "Steem USD",
    "DENT-USD": "Dent USD",
    "ORBS-USD": "Orbs USD",
    "SYN12147-USD": "Synapse USD",
    "LOCUS-USD": "Locus Chain USD",
    "EVER-USD": "Everscale USD",
    "CFG-USD": "Centrifuge USD",
    "XPLA-USD": "XPLA USD",
    "COTI-USD": "COTI USD",
    "MVL-USD": "MVL USD",
    "DKA-USD": "dKargo USD",
    "ERG-USD": "Ergo USD",
    "DERO-USD": "Dero USD",
    "LOOKS-USD": "LooksRare USD",
    "MBOX-USD": "MOBOX USD",
    "RDNT-USD": "Radiant Capital USD",
    "ALPHA-USD": "Alpha Venture DAO USD",
    "ARDR-USD": "Ardor USD",
    "PROM-USD": "Prom USD",
    "POWR-USD": "Powerledger USD",
    "VTHO-USD": "VeThor Token USD",
    "NKN-USD": "NKN USD",
    "WNXM-USD": "Wrapped NXM USD",
    "REN-USD": "Ren USD",
    "EWT-USD": "Energy Web Token USD",
    "XVS-USD": "Venus USD",
    "NYM-USD": "NYM USD",
    "RBN-USD": "Ribbon Finance USD",
    "REP-USD": "Augur USD",
    "ALI16876-USD": "Artificial Liquid Intelligence USD",
    "HOOK-USD": "Hooked Protocol USD",
    "CQT-USD": "Covalent USD",
    "UOS-USD": "Ultra USD",
    "STRAX-USD": "Stratis USD",
    "CTC-USD": "Creditcoin USD",
    "WIN-USD": "WINkLink USD",
    "POND-USD": "Marlin USD",
    "VBG-USD": "Vibing USD",
    "PHA-USD": "Phala Network USD",
    "ARPA-USD": "ARPA USD",
    "MTL-USD": "Metal DAO USD",
    "CTK4807-USD": "Shentu USD",
    "MNW-USD": "Morpheus.Network USD",
    "XSGD-USD": "XSGD USD",
    "BNT-USD": "Bancor USD",
    "IQ-USD": "IQ USD",
    "OXT-USD": "Orchid USD",
    "BETA-USD": "Beta Finance USD",
    "VEGA-USD": "Vega Protocol USD",
    "FX-USD": "Function X USD",
    "SPELL-USD": "Spell Token USD",
    "ALICE-USD": "MyNeighborAlice USD",
    "MDX-USD": "Mdex USD",
    "NU-USD": "NuCypher USD",
    "DUSK-USD": "Dusk Network USD",
    "FUN-USD": "FUNToken USD",
    "OAS-USD": "Oasys USD",
    "BBF-USD": "Bubblefong USD",
    "QKC-USD": "QuarkChain USD",
    "AIDOGE-USD": "ArbDoge AI USD",
    "VBUSD-USD": "Venus BUSD USD",
    "HIGH-USD": "Highstreet USD",
    "ANKRETH-USD": "Ankr Staked ETH USD",
    "DODO-USD": "DODO USD",
    "LOOM-USD": "Loom Network USD",
    "SOLO-USD": "Sologenic USD",
    "GAFI-USD": "GameFi.org USD",
    "CORE-USD": "cVault.finance USD",
    "AURA21532-USD": "Aura Finance USD",
    "TLM-USD": "Alien Worlds USD",
    "TON-USD": "Tokamak Network USD",
    "CEEK-USD": "CEEK VR USD",
    "IDEX-USD": "IDEX USD",
    "XYO-USD": "XYO USD",
    "DEXT-USD": "DEXTools USD",
    "MFT-USD": "Hifi Finance (Old) USD",
    "UTK-USD": "Utrust USD",
    "BFC7817-USD": "Bifrost USD",
    "SUPER8290-USD": "SuperVerse USD",
    "VAI-USD": "Vai USD",
    "COL-USD": "Clash of Lilliput USD",
    "WMT-USD": "World Mobile Token USD",
    "DAR-USD": "Mines of Dalarnia USD",
    "RINGX-USD": "RING X PLATFORM USD",
    "SFUND-USD": "Seedify.fund USD",
    "SUN-USD": "Sun (New) USD",
    "ARRR-USD": "Pirate Chain USD",
    "CEL-USD": "Celsius USD",
    "TSUKA-USD": "Dejitaru Tsuka USD",
    "LINA7102-USD": "Linear Finance USD",
    "e-Radix": "e-Radix USD",
    "MBX18895-USD": "MARBLEX USD",
    "EUROC-USD": "Euro Coin USD",
    "RACA-USD": "RACA USD",
    "LADYS-USD": "Milady Meme Coin USD",
    "TRU7725-USD": "TrueFi USD",
    "MCB-USD": "MUX Protocol USD",
    "REEF-USD": "Reef USD",
    "ORC-USD": "Orclands Metaverse USD",
    "VRSC-USD": "VerusCoin USD",
    "RAMP-USD": "RAMP USD",
    "AERGO-USD": "Aergo USD",
    "AXEL-USD": "AXEL USD",
    "TLOS-USD": "Telos USD",
    "CWEB-USD": "Coinweb USD",
    "BADGER-USD": "Badger DAO USD",
    "AMPL-USD": "Ampleforth USD",
    "CCD-USD": "Concordium USD",
    "OGN-USD": "Origin Protocol USD",
    "SUSD-USD": "sUSD USD",
    "WRX-USD": "WazirX USD",
    "BSW-USD": "Biswap USD",
    "ARK-USD": "Ark USD",
    "ATA-USD": "Automata Network USD",
    "SSX-USD": "SOMESING USD",
    "QUACK-USD": "RichQUACK.com USD",
}
